spring:
  application:
    name: Patients-MD

  datasource:
    url: jdbc:mysql://localhost:3306/nutricab_db?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
    username: root          # ou ton user MySQL
    password:           # ou ton password MySQL
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true
server:
  port: 8182

app:
  security:
    auth:
      login-checks-enabled: false
      authorization-checks-enabled: false
    cors:
      allowed-origins: http://localhost:4200
    cookies:
      secure: false
      same-site: Lax
    jwt:
      issuer: patients-md
      secret: ${JWT_SECRET:NutriCab_JWT_Secret_Key_2026_x7#kL9$mP2@vR5}
      expiration-minutes: 60
      refresh-expiration-days: 7

logging:
  level:
    com.bd.patientsmd: DEBUG
    org.springframework.web: INFO
    org.springframework.transaction.interceptor: TRACE
    org.springframework.orm.jpa: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE
