spring:
  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/nutricab_db?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true

app:
  security:
    cookies:
      secure: false
      same-site: Lax

logging:
  level:
    com.bd.patientsmd: DEBUG
    org.springframework.web: INFO
    org.springframework.transaction.interceptor: TRACE
    org.springframework.orm.jpa: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE
